### ISSUE TITLE
StorageClass volPrefix has no effect to the volume name

### ISSUE THREAD

**Issue by dewongway** [Seagate/seagate-exos-x-csi#57]
**Describe the bug**
I am not sure what the volPrefix supposed to do. When I set it to csi-me5, I don't see it being taken into consideration for the PVC name, PV name, or the volume name on the storage array.

**To Reproduce**

Set volPrefix in the storageclass and create a PV using the storage class.

```
apiVersion: storage.k8s.io/v1
kind: StorageClass
provisioner: csi-exos-x.seagate.com
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
metadata:
  name: me5-2-storageclass2
parameters:
  csi.storage.k8s.io/provisioner-secret-name: seagate-exos-x-csi-secrets
  csi.storage.k8s.io/provisioner-secret-namespace: seagate
  csi.storage.k8s.io/controller-publish-secret-name: seagate-exos-x-csi-secrets
  csi.storage.k8s.io/controller-publish-secret-namespace: seagate
  csi.storage.k8s.io/controller-expand-secret-name: seagate-exos-x-csi-secrets
  csi.storage.k8s.io/controller-expand-secret-namespace: seagate
  fsType: ext4
  pool: A
  volPrefix: csi-me5
  storageProtocol: iscsi
```

```
$ kubectl get pvc -n test-seagate
NAME         STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS          AGE
me5-2-pvc2   Bound    pvc-c1312963-2c5d-4a77-8b71-6d23d541e623   30Gi       RWO            me5-2-storageclass2   5m41s

$ kubectl get pv -n test-seagate
NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM                     STORAGECLASS                 REASON   AGE
pvc-c1312963-2c5d-4a77-8b71-6d23d541e623   30Gi       RWO            Delete           Bound    test-seagate/me5-2-pvc2   me5-2-storageclass2                   5m20s
```

![image](https://user-images.githubusercontent.com/27778629/213612364-58bf8d41-31ea-4060-a7ff-e6cbd96b2eb1.png)

**Expected behavior**
I expect to see the prefix as part of the volume name.

**Screenshots**

**Storage System (please complete the following information):**
 - Vendor:  Dell PowerVault ME5
 - Model
 - Firmware Version: ME5.1.0.1.0

**Environment:**
 - Kubernetes version: v1.24.4+rke2r1
 - Host OS: SUSE Linux Enterprise Server 15 SP3

**Additional context**

**Comment by seagate-chris** [comment]
Thanks, we're looking into this now.

**Comment by seagate-chris** [comment]
The limit for the VolNamePrefix parameter is 3 characters, so your input "csi-me5" was silently truncated to "csi".  We'll update the examples and add a warning in the logs to make this clearer.

**Comment by dewongway** [comment]
Great. Thanks for the info.
