### ISSUE TITLE
not support iscsi chap authentication？

### ISSUE THREAD

**Issue by suningxiao** [Seagate/seagate-exos-x-csi#77]
not support iscsi chap authentication？

**Comment by seagate-chris** [comment]
You can use CHAP if you place the necessary CHAP parameters in the /etc/iscsi/iscsid.conf file on your Kubernetes worker nodes.  For example, add this to /etc/iscsi/iscsid.conf:

> node.session.auth.authmethod = CHAP
> node.session.auth.username = common
> node.session.auth.password = randompassword

and on the array set the same parameters:

> set chap-record name common secret randompassword
> set iscsi-parameters chap enabled

Please let us know if this wouldn't work for your environment.  Currently we don't have a more elegant solution (CSI does not seem to support CHAP well) but we're working on it.

**Comment by suningxiao** [comment]
Thank you, it work.

**Comment by gregnsk** [comment]
@suningxiao  are you planning to attend Kubecon in November? We would be glad to meet in person and talk about your experience with our CSI driver. Please reach out to me at gregory.touretsky AT seagate.com
